stages:
    - test

run_tests:
    stage: test
    image: python
    artifacts:
        when: always
        expire_in: 5 days
        paths:
            - allure-report
    before_script:
      # ключ подписи
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
      # Установка Google Chrome
      - apt-get update && apt-get install -y google-chrome-stable
      # Установка зависимостей
      - pip install -r requirements.txt
      # Установка Allure
      - apt update && apt install -y openjdk-17-jdk openjdk-17-jre
      - wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && tar -zxvf allure-2.32.0.tgz -C /opt/ && ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure

      - pip install selenium --upgrade

    script:
        - pytest -v --alluredir=allure-results
    after_script:
      - allure generate -c allure-results -o allure-report