name: Run Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг для checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг для настройки Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Шаг для установки зависимостей
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг для установки Allure
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      # Шаг для выполнения тестов
      - name: Run tests
        run: pytest --alluredir=allure-results

      # Шаг для генерации отчета Allure
      - name: Generate Allure report
        run: allure generate allure-results -o allure-report --clean

      # Шаг для создания и деплоя на ветку gh-pages
      - name: Create and Deploy to gh-pages branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Проверка, существует ли ветка gh-pages
          git fetch origin
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "Branch gh-pages exists, no need to create it."
          else
            # Если ветки нет, создаем ее
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi

          # Переход на ветку gh-pages и добавление сгенерированного отчета
          git checkout gh-pages
          git rm -rf .
          cp -r allure-report/* .
          git add .
          git commit -m "Deploy Allure report"
          git push origin gh-pages

      # Публикация ссылки на отчет
      - name: Publish Allure report link
        run: |
          echo "Allure report is available at: https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/allure-report/index.html"
