name: Run Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  # Создаем директорию для истории Allure
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Remove old allure-report directory
        run: |
          sudo rm -rf allure-report  # Удаляем старый отчет

      - name: Generate Allure report without --clean to preserve history
        run: allure generate allure-results -o allure-report

      - name: Commit Allure report to gh-pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Переход на ветку gh-pages
          git checkout gh-pages

          # Копируем новый отчет на gh-pages
          cp -r allure-report/* .

          # Добавляем и пушим изменения
          git add .
          git commit -m "Deploy Allure report"
          git push origin gh-pages

      - name: Publish Allure report link
        run: |
          echo "Allure report is available at: https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/allure-report/index.html"
