name: Run Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  # Джоба для тестов и генерации отчета
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      allure_report_dir: ${{ steps.deploy-allure-report.outputs.allure_report_dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

  # Джоба для деплоя отчета на GitHub Pages
  deploy-report:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup history directory for Allure
        run: |
          # Создаем директорию для истории Allure, если ее нет
          sudo mkdir -p allure-results/history

          # Переходим в директорию gh-pages и сохраняем предыдущие отчеты
          if [ -d "./allure-report" ]; then
            sudo cp -r ./allure-report/* ./allure-results/history/
          fi

      - name: Deploy Allure Report to GitHub Pages
        id: deploy-allure-report
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: allure-report
          clean: false  # Убираем очистку папки, чтобы не удалять старые отчеты

      - name: Output Allure report link
        run: |
          echo "Allure report is available at: https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/allure-report/index.html"
