name: Run Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download previous test history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      - name: Download previous test history
        run: |
          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=allure-results" | python -c "import sys, json; artifacts=json.load(sys.stdin)['artifacts']; print(artifacts[0]['id'] if artifacts else None);")
          
          if [ "$ARTIFACT_ID" != "None" ]; then
            echo "Found previous allure-results artifact, downloading..."
            curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip -o previous_results.zip
            mkdir allure-results && unzip previous_results.zip -d allure-results
          else
            echo "No previous allure-results artifacts found, proceeding with fresh run."
          fi

  test:
    runs-on: ubuntu-latest
    needs: download-history
    name: Run Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate Allure report

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'

      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report

  deploy-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Deploy Allure report

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit Allure report to gh-pages
        run: |
          # Переход на ветку gh-pages
          git checkout gh-pages

          # Создаем папку с уникальным именем для каждого отчета (например, по дате)
          REPORT_DIR="allure-report-$(date +'%Y-%m-%d_%H-%M-%S')"
          mkdir $REPORT_DIR
          
          # Копируем отчет в новую папку
          cp -r allure-report/* $REPORT_DIR/

          # Добавляем и пушим изменения
          git add .
          git commit -m "Deploy Allure report at $REPORT_DIR"
          git push origin gh-pages

      - name: Publish Allure report link
        run: |
          # Публикуем ссылку на последний отчет
          echo "Allure report is available at: https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/$REPORT_DIR/index.html"
