name: UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Шаг для получения кода из репозитория
      - uses: actions/checkout@v2

      # Шаг для установки Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг для установки Chrome и ChromeDriver
      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-driver

      # Шаг для выполнения UI-тестов с использованием pytest
      - name: Run UI tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pytest -sv --alluredir=allure-results

      # Шаг для генерации отчета Allure
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      # Шаг для деплоя отчета на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
