name: Run Tests and Deploy Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      - name: Download previous test history
        run: |
          ARTIFACT_ID=$(curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=allure-results" | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip -o previous_results.zip
          mkdir allure-results && unzip previous_results.zip -d allure-results

      - name: Run tests
        run: pytest --alluredir=allure-results

      - name: Generate Allure report
        run: allure generate allure-results -o allure-report

      - name: Commit Allure report to gh-pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Переход на ветку gh-pages
          git checkout gh-pages

          # Создаем папку с уникальным именем для каждого отчета (например, по дате)
          REPORT_DIR="allure-report-$(date +'%Y-%m-%d_%H-%M-%S')"
          mkdir $REPORT_DIR
          
          # Копируем отчет в новую папку
          cp -r allure-report/* $REPORT_DIR/

          # Добавляем и пушим изменения
          git add .
          git commit -m "Deploy Allure report at $REPORT_DIR"
          git push origin gh-pages

      - name: Publish Allure report link
        run: |
          # Публикуем ссылку на последний отчет
          echo "Allure report is available at: https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY/$REPORT_DIR/index.html"

