name: UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Шаг для получения кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг для установки Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Шаг для установки зависимостей
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Шаг для установки Allure
      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre curl tar
          curl -o allure-2.17.2.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.2/allure-commandline-2.17.2.tgz
          tar -zxvf allure-2.17.2.tgz -C /opt/
          sudo ln -s /opt/allure-2.17.2/bin/allure /usr/local/bin/allure
          rm allure-2.17.2.tgz

      # Шаг для получения ID артефакта
      - name: Get Artifact ID
        run: |
          # Запросить список артефактов из GitHub API
          artifact_list=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts)

          # Извлечь ID последнего артефакта (первого в списке)
          artifact_id=$(echo "$artifact_list" | jq -r '.artifacts[0].id')
          echo "Artifact ID: $artifact_id"
          echo "ARTIFACT_ID=$artifact_id" >> $GITHUB_ENV

      # Шаг для скачивания артефакта
      - name: Download Artifact
        run: |
          # Использовать ARTIFACT_ID для скачивания последнего артефакта из GitHub
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -o artifact.zip \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip

      # Шаг для распаковки артефакта
      - name: Unzip artifact
        run: |
          # Распаковать скачанный артефакт
          unzip artifact.zip -d artifact

      # Шаг для копирования директорий history и pages
      - name: Copy history and pages directories
        run: |
          # Копировать необходимые директории (с флагом -R для копирования содержимого)
          cp -R artifact/history allures/history
          cp -R artifact/pages allures/pages

      # Шаг для выполнения тестов с использованием pytest
      - name: Run tests
        run: pytest --alluredir=allure-results

      # Шаг для генерации отчета Allure
      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      # Шаг для деплоя отчета на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
