name: Allure to server

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: all
        type: choice
        options:
          - first_test
          - second_test
          - all

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" == "first_test" ]; then
            pytest tests/test_button.py::test_button_exist --alluredir=allure-results
          elif [ "${{ github.event.inputs.deployment_target }}" == "second_test" ]; then
            pytest tests/test_button.py::test_button_exist_2 --alluredir=allure-results
          else
            pytest --alluredir=allure-results
          fi

      - name: Zip allure results
        run: |
          sudo apt install zip
          zip -r allure-results.zip allure-results

      - name: Upload results
        run: |
          curl -X "POST" "http://<your-server>/api/result" \
            -H 'accept: */*' \
            -H 'Content-Type: multipart/form-data' \
            -F 'allureResults=@allure-results.zip;type=application/zip' \
            | python3 -c "import sys, json; print(json.load(sys.stdin)['uuid']);" \
            | xargs -I {} curl -X 'POST' "http://<your-server>/api/report" \
              -H 'accept: */*' \
              -H 'Content-Type: application/json' \
              -d "{\"reportSpec\":{\"path\":[\"pathstring\"],\"executorInfo\":{\"name\":\"GitHub\",\"type\":\"exectype\",\"url\":\"https://github.com/${GITHUB_REPOSITORY}/actions/workflows/server.yml\",\"buildOrder\":0,\"buildName\":\"$GITHUB_RUN_NUMBER\",\"buildUrl\":\"https://github.com/${GITHUB_REPOSITORY}/actions/runs/$GITHUB_RUN_ID\",\"reportName\":\"my_report_name\",\"reportUrl\":\"my_report_url\"}},\"results\":[\"{}\"],\"deleteResults\":true}"

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 1
